### ISSUE TITLE
calling shipment.add_package more than once results in "Invalid package count or invalid package sequence number. (Error code: 2021)"

### ISSUE THREAD

**Issue by preston-wagner** [python-fedex-devs/python-fedex#105]
When I call `shipment.add_package` more than once, it appears that the api is sent `<ns0:PackageCount>0</ns0:PackageCount>`, and the response includes `<Code>2021</Code><Message>Invalid package count or invalid package sequence number.</Message>`.

**Comment by preston-wagner** [comment]
I'm creating the package with
`def create_package(shipment, json_package):
    package_weight = shipment.create_wsdl_object_of_type('Weight')
    package_weight.Value = float(json_package['weight'])
    package_weight.Units = "LB"
    fedex_package = shipment.create_wsdl_object_of_type('RequestedPackageLineItem')
    fedex_package.Weight = package_weight
    if json_package['width']:
        package_dimensions = shipment.create_wsdl_object_of_type('Dimensions')
        package_dimensions.Width = int(float(json_package['width']))
        package_dimensions.Length = int(float(json_package['length']))
        package_dimensions.Height = int(float(json_package['height']))
        package_dimensions.Units = "IN"
        fedex_package.Dimensions = package_dimensions
    return fedex_package`
and adding it to the shipment with
`for package in packages:
        shipment.add_package(create_package(shipment, package))`

**Comment by preston-wagner** [comment]
The shipment itself is created with
```
    shipment = FedexProcessShipmentRequest(CONFIG_OBJ)
```
like in the example code.

**Comment by preston-wagner** [comment]
Here's what Fedex said about this issue
> Thank you for using FedEx Online Support. In answer to your question, when sending a ProcessShipmentRequest or ValidateShipmentRequest via Web Services for a multiple piece shipment, only one package can be submitted in a single transaction, so additional transactions are needed for each child package. The PackageCount element should reflect the total number of packages in a shipment, while the first package should have a SequenceNumber value of 1. No other instances of RequestedPackageLineItems should be submitted in this first request. When you receive a response for this transaction, you will see a tracking number value in the element MasterTrackingId. This value should be supplied using the MasterTrackingId element in each child request to tie the packages together as a Multiple Piece Shipment.
So it seems to me that the `add_package` method won't work correctly for multi-package shipments.

**Comment by preston-wagner** [comment]
(Sorry, I hit the wrong comment button.)

**Comment by radzhome** [comment]
so i think they answered your question, send only one package per ProcessShipmentRequest or ValidateShipmentRequest

**Comment by vijayjava15** [comment]
Hai , I am working on FedEx add shipment api, i have 80 packages am splitting it in two and making a api call twice. I am facing the same issue . Can't we make api call twice in add package???
