### ISSUE TITLE
rate_request returning urllib.error.URLError & ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by iguzmanl** [python-fedex-devs/python-fedex#108]
After updating ```example_config.py``` with my credentials, running `python3 rate_request.py` returns ```ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051).---- During handling of the above exception, another exception occurred: ---- urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)>```

Do I need to add any more changes to other files? I could only think that my credentials are incorrect. I did not change any other files.

The full log output here: https://gist.github.com/iguzmanl/6a5385262b036dfe906bf5642f84b1ee

**Comment by radzhome** [comment]
By googling, I found this - https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3 . Not using this module at the moment, but if you figure it out, update it here.

**Comment by tashaunthill** [comment]
Had the same issue, but resolved it with the below steps:

Browse to Applications/Python 3.6 and double-click Install Certificates.command
