### ISSUE TITLE
Authentication error on live account. But direct SOAP request working

### ISSUE THREAD

**Issue by arunssjoshi** [python-fedex-devs/python-fedex#112]
I have configured fedex credentials in test mode it works without any issue. But When I updated the credentials to live account , it shows authentication error. I could call the rate api in direct SOAP method in postman and it is working.

**Comment by Jukka-Sarasti** [comment]
bump

**Comment by radzhome** [comment]
Your creds probably don't have access to rate api. I would ask fedex.
