### ISSUE TITLE
Pass Pickup Date to Rate Request

### ISSUE THREAD

**Issue by Helix31522** [python-fedex-devs/python-fedex#114]
Does anyone know how to pass a pickup date to the rate request module?

I see in rate_service.py that the pickup date is hard coded:

`self.RequestedShipment.ShipTimestamp = datetime.datetime.now()`

I am not familiar enough with the library to make modifications. 

Thank for your help!

**Comment by radzhome** [comment]
This is a wrapper so you can build your own request with this package without modifying the code.
