### ISSUE TITLE
International Commodities- FedexShipmentCreateRequest

### ISSUE THREAD

**Issue by jeenal-gajjar** [python-fedex-devs/python-fedex#117]
fedex.base_service.FedexError: Commodities are required (Error code: 6065)

This is the error which I got during the International Shipment Create. I don't know how to add Commodities in FedEx Python API. 

Need your help urgent basis.

**Comment by radzhome** [comment]
We currently don't have an international shipment example, so if you get one working go ahead and add it in examples/ as a PR.
