### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by sharoonthomas** [python-fedex-devs/python-fedex#120]
Hey folks, first of all, thank you for maintaining this library.

The currently released version is quite old and some features don't work on the released WSDLs like the direct signature requirement. Is there a planned release date on pypi for the next release?

**Comment by dlstadther** [comment]
It looks like there was a [WSDL update 8/15/2018](https://github.com/python-fedex-devs/python-fedex/commit/e4a87212b43dd7e43d0aa936b9a7591c5c7ca1f1) which never had a new PyPi release. It'd be great to release v2.5.0 or something

**Comment by dlstadther** [comment]
@radzhome Could you please release version 2.5.0 (including the 2018-08 WSDL) to PyPi? Much appreciated!

**Comment by gozzals** [comment]
looking forward to the next release, perhaps it includes the international shipping.
much appreciated
A.

**Comment by hiaselhans** [comment]
:+1:   :)

**Comment by gozzals** [comment]
Hi All -
Trying to add Commodity items to the existing code, ( so I can use the code for international shipping )
1- Adding these 2 lines to Lib\fedex\services\ship_service.pycommodity = self.client.factory.create('Commodity')
commodity.Name = self.client.factory.create('Name')

2- Adding this line to create_shipment.py ( one of the example files )shipment.commodity.Name = 'RTX1080-1'
when running, getting   suds.TypeNotFound: Type not found: 'Name'
What could be the problem ?  
Appreciate any comment.
Please note, the file Lib\fedex\wsdl\test_server_wsdl\ShipService_v17.wsdl    contains the Comodity line # 513
ThanksA.    On Thursday, January 30, 2020, 02:04:17 AM PST, simon klemenc <notifications@github.com> wrote:  
 
 
👍 :)

**Comment by radzhome** [comment]
You can use the master branch, development release until there is time to do one.

**Comment by radzhome** [comment]
I have to find sometime to do it, soon

**Comment by radzhome** [comment]
@dlstadther @sharoonthomas @gozzals @hiaselhans  DONE :)
