### ISSUE TITLE
address validation

### ISSUE THREAD

**Issue by sivakumarb-nalashaa** [python-fedex-devs/python-fedex#122]
Hi All,

I am getting success for the address validation. suppose if pass all parameters empty
{
	"street": "",
	"city": "",
	"state": "",
	"postal_code": 0,
	"country": "",
	"residential": "True"
}
Service  Method:- FedexAddressValidationRequest
Response: {
 {
        "HighestSeverity": "SUCCESS",
        "Notifications": [
            {
                "Severity": "SUCCESS",
                "Source": "wsi",
                "Code": "0",
                "Message": "Success"
            }
        ],
        "Version": {
            "ServiceId": "aval",
            "Major": 4,
            "Intermediate": 0,
            "Minor": 0
        },
        "ReplyTimestamp": "2019-07-28T02:21:51-05:00",
        "AddressResults": [
            {
                "State": "RAW",
                "Classification": "UNKNOWN",
                "EffectiveContact": {
                    "PersonName": null,
                    "CompanyName": null,
                    "PhoneNumber": null
                },
                "EffectiveAddress": {
                    "City": null,
                    "StateOrProvinceCode": null,
                    "PostalCode": "0",
                    "UrbanizationCode": null,
                    "CountryCode": null
                },
                "ParsedAddressPartsDetail": ""
            }
        ]
    }
}
its returning Success. How its working. Any help?

**Comment by radzhome** [comment]
Ask fedex, this is just a wrapper. It seems its returning success with "Classification": "UNKNOWN",
