### ISSUE TITLE
The number of RequestedPackages in the RequestedShipment must be equal to 1

### ISSUE THREAD

**Issue by sivakumarb-nalashaa** [python-fedex-devs/python-fedex#123]

**Comment by vishal-manani** [comment]
I am also facing the same problem could you please help me out?

**Comment by sivakumarb-nalashaa** [comment]
> I am also facing the same problem could you please help me out?

@vishal-manani  Can you send me the code If possible I can help you.

**Comment by vishal-manani** [comment]
shipment = FedexProcessShipmentRequestChild(self.CONFIG_OBJ)
shipment.RequestedShipment.DropoffType = 'BUSINESS_SERVICE_CENTER'
shipment.RequestedShipment.ServiceType = 'FEDEX_GROUND'
shipment.RequestedShipment.PackagingType = 'YOUR_PACKAGING'

shipment.RequestedShipment.Shipper.Contact.PersonName = "Person name"
shipment.RequestedShipment.Shipper.Address.StreetLines = "Address"

shipment.RequestedShipment.Recipient.Contact.PersonName = "Person name"
shipment.RequestedShipment.Recipient.Address.StreetLines = "Address"

# =========== package 1 ====================

package1_weight = shipment.create_wsdl_object_of_type('Weight')
package1_weight.Value = '10'
package1_weight.Units = "LB"

package1_dimensions = shipment.create_wsdl_object_of_type('Dimensions')
package1_dimensions.Length = 10
package1_dimensions.Width = 10
package1_dimensions.Height = 10
package1_dimensions.Units = "IN"

package1 = shipment.create_wsdl_object_of_type('RequestedPackageLineItem')            
package1.PhysicalPackaging = 'BOX'
package1.Weight = package1_weight
package1.Dimensions = package1_dimensions

shipment.add_package(package1)

# =========== package 2 ====================

package2_weight = shipment.create_wsdl_object_of_type('Weight')
package2_weight.Value = '10'
package2_weight.Units = "LB"

package2_dimensions = shipment.create_wsdl_object_of_type('Dimensions')
package2_dimensions.Length = 10
package2_dimensions.Width = 10
package2_dimensions.Height = 10
package2_dimensions.Units = "IN"

package2 = shipment.create_wsdl_object_of_type('RequestedPackageLineItem')            
package2.PhysicalPackaging = 'BOX'
package2.Weight = package2_weight
package2.Dimensions = package2_dimensions

shipment.add_package(package2)

shipment.send_request()

**Comment by sivakumarb-nalashaa** [comment]
@vishal-manani Try to add this parameters in each RequestedPackageLineItems.
RequestedPackageLineItems.SequenceNumber
RequestedPackageLineItems.GroupNumber
RequestedPackageLineItems.GroupPackageCount

make sure SequenceNumber should increment for each package but, GroupNumber and GroupPackageCount always 1. 
Try this.

**Comment by sivakumarb-nalashaa** [comment]
@vishal-manani I able to pull the domestic rates for the multiple packages.
You should add few more paramters to RequestedPackageLineItem

RequestedPackageLineItem.GroupPackageCount = 1 # always should keep value 1
RequestedPackageLineItem.GroupNumber = 1 # always should keep value 1
RequestedPackageLineItem.SequenceNumber = 1 # increment the value for each package.

Try this.

**Comment by vishal-manani** [comment]
I'm trying with this code but still getting same error.

**Comment by sivakumarb-nalashaa** [comment]
Are you pulling rates or creating shipment?

**Comment by vishal-manani** [comment]
creating shipment

**Comment by sivakumarb-nalashaa** [comment]
I haven't started shipment for MPS. I need to start. Once it is done then i will let u know.
