### ISSUE TITLE
Tracking more then one package?

### ISSUE THREAD

**Issue by MOwsianowski** [python-fedex-devs/python-fedex#129]
Hello,

Can you let me know if there is a possibility to track more then one package with single api call?

Thanks,
Marek

**Comment by thenaturalist** [comment]
+1 This should be possible according to Fedex Docs.

**Comment by radzhome** [comment]
in which version of the wsdl, we are on 16 - 
https://github.com/python-fedex-devs/python-fedex/blob/master/fedex/wsdl/TrackService_v16.wsdl#L1580

Should be possible yes, https://github.com/python-fedex-devs/python-fedex/blob/master/fedex/wsdl/TrackService_v16.wsdl#L1578

If you get it working feel free to open a PR with the example.
