### ISSUE TITLE
Adding contents of the package as line items

### ISSUE THREAD

**Issue by MatinF** [python-fedex-devs/python-fedex#130]
Hi all,

We'd like to use the wrapper, but we're in doubt how to add the items in our shipments. Typically we have between 1 and 8 different items in a package, which we currently register manually in the FedEx web platform. 

Is there a way to do this in the wrapper? I could not find this in the examples.

![image](https://user-images.githubusercontent.com/26184427/69159726-ac710580-0ae8-11ea-929d-a546b1b95c2e.png)

**Comment by radzhome** [comment]
Its just a wrapper to the API, SO you should look through the xml file and see how its done. If you get it, go ahead and send a PR as an example.
