### ISSUE TITLE
How to generate multiple-package shipments?

### ISSUE THREAD

**Issue by ph15041996** [python-fedex-devs/python-fedex#132]
I tried to generate multiple-package shipments using the "create_shipment.py" but got "Fedex.base_service.FedexError: The number of RequestedPackages in the RequestedShipment must be equal to 1 (Error code: 2463)". What is the proper way to generate multiple-package shipments??

**Comment by MOwsianowski** [comment]
For Master piece (first piece) you declare:
shipment.RequestedShipment.PackageCount = <pieces_count>
package_piece_master.SequenceNumber = 1
..... send request for creating master
For second piece:
package1.SequenceNumber = 2
shipment.RequestedShipment.MasterTrackingId.TrackingIdType = 'FEDEX'
shipment.RequestedShipment.MasterTrackingId.TrackingNumber = <master_tracking>
..... send request for creating second piece
Create each piece with SequenceNumber+=1
Last piece must be equal to <pieces_count>

**Comment by ph15041996** [comment]
Thanks . Its working Now.

**Comment by nicogasque** [comment]
This is not working for me, the (package_piece_master.SequenceNumber = 1) is undefined variable.

Does anyone have the complete code to make it work?
