### ISSUE TITLE
Possible Error in Documentation

### ISSUE THREAD

**Issue by abid-celltech** [python-fedex-devs/python-fedex#146]
Hello,

I tried 

`from fedex.tools.response_tools import sobject_to_dict`

which results in an Attribute error. I got this code from [Quick Start Docs](https://python-fedex.readthedocs.io/en/stable/quick_start.html#get-json-and-dictionary-response)

I believe the code should now be:

`from fedex.tools.conversion import sobject_to_json`

Not sure if I'm missing something here.

**Comment by radzhome** [comment]
This is true the latest doc is not up, have to re-upload docs for latest version. The one you are looking at is for an older version.
