### ISSUE TITLE
Possible to convert JSON to WSDL object?

### ISSUE THREAD

**Issue by p-doyle** [python-fedex-devs/python-fedex#149]
Is it possible to use JSON to, for example, populate fields in TrackSelectionDetail?  I was hoping to be able to use something like the below:

`{'ShipmentAccountNumber': '1234', 'PackageIdentifier':  {'Type': 'SHIPPER_REFERENCE', 'Value': 'myreference'}}`

I see there are helper functions to convert from WSDL to dict but didn't see anything to do the reverse... is this possible?

Thanks for the great library!

**Comment by radzhome** [comment]
There is no helper now, it could be done yeah.

**Comment by radzhome** [comment]
send a PR if you have, I will close
