### ISSUE TITLE
Significant Change in json field names on track request 2.4.0 ==> 2.4.1

### ISSUE THREAD

**Issue by brianhwitte** [python-fedex-devs/python-fedex#153]
Simplified use case for python-fedex:
```
import json
from fedex.services.track_service import FedexTrackRequest
from fedex.tools.conversion import sobject_to_json

def get_delivered_at_time(tracking_number):
    track_request = FedexTrackRequest(fedex_config_object)
    track_request.SelectionDetails.PackageIdentifier.Value = tracking_num
    track_request.SelectionDetails.PackageIdentifier.Type = 'TRACKING_NUMBER_OR_DOORTAG'

    # remove FedEx operating company from request
    del track_request.SelectionDetails.OperatingCompany 
    
    track_request.send_request()
    json_response = sobject_to_json(track_request.response)
    json_response = json.loads(json_response)

    tracking_details = json_response['CompletedTrackDetails'][0]['TrackDetails']
    if 'ActualDeliveryTimestamp' in tracking_details:
         do stuff

```

It looks like the `ActualDeliveryTimestamp` was removed from the ~~specifications for `sobject_to_json`~~ wsdl specifications used by fedex-python between 2.4.0 and 2.4.1 ([see here](https://github.com/python-fedex-devs/python-fedex/commit/535c80ead5064e48d1c1445bf81979c7c4cd1643#diff-e3b1f4b015118a39c1a17c75d9504a4a6f101d18b0821c439421a31d20633ea8L1490
))

As a result, our code cannot get the essential data from the fedex api response, and the "do stuff" block in our code is unreachable.

I didn't see anything in a changelog about the update.  When I contacted Fedex developer support, they claim that no updates were made to the structure of the data they send out.

1.  Are we using the package incorrectly?
2. Where would I find out about breaking changes like this?

UPDATED to clarify my question as I understand the changes.

**Comment by radzhome** [comment]
Use the old version or adapt your code to the new wsdl
