### ISSUE TITLE
Updating Ship Service to version 26 including WSDL File ShipService_v26

### ISSUE THREAD

**Issue by vantyecw** [python-fedex-devs/python-fedex#154]
First of all, thank you for this great package!

Just wondering if this package is still compatible with newer version of Ship API (version 26)? 

In order to use the newer version of Ship API, I would need to replace the file "ShipService_v23.wsdl" that is in 'wsdl' folder with the file "ShipService_v26.wsdl". Just wondering if it will be sufficient to just specify `wsdl_path` in `FedexConfig` to point to the folder containing "ShipService_v26.wsdl" file and also override `FedexProcessShipmentRequest` class to setup `_version_info` and `_config_obj` object?

Otherwise, what should I do in order to use this package with the latest version of Fedex API?

Thanks in advance!

**Comment by zesriver** [comment]
It doesn't seem to be compatible. I'm looking forward to the release of the ShipService_v26 WSDL compatible version.
