### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jerodg** [python-fedex-devs/python-fedex#163]
How can I install this module using suds in lieu of suds-jurko? suds-jurko is very outdated and I can't get it to install on modern python but I can get suds to install. When suds-jurko fails the entire fedex package fails.

**Comment by amdemas** [comment]
It looks like the latest commit removed suds-jurko. However, the maintainer hasn't released a new version on PyPI. :( 

https://github.com/python-fedex-devs/python-fedex/commit/8d74623123153205d72bb18b774a632ee92972f4

You can install the package from that commit point with

`pip install git+https://github.com/python-fedex-devs/python-fedex.git@8d74623123153205d72bb18b774a632ee92972f4`

Hopefully, the maintainer will push a release soon.

**Comment by radzhome** [comment]
I don't maintain this anymore but I did merge to master
