### ISSUE TITLE
New maintainer available

### ISSUE THREAD

**Issue by radzhome** [python-fedex-devs/python-fedex#52]
Hi,

On behalf of FanXchange.com (github.com/fanxchange), I would like to propose us to be the new maintainer for your package.

Cheers, Rad

**Comment by gtaylor** [comment]
Thanks for expressing interest. I need to hammer out a quick transition plan, but we can move forward pretty soon. I am obviously not too responsive on python-fedex anymore, which is no good for the users.

**Comment by radlws** [comment]
Glad to hear it, looking forward to keeping this package current!

**Comment by radlws** [comment]
I wanted to get a new release out to pypi, what do you think? Also, before it goes out, I want to support suds-jurko, but at the same time be compatible with suds 0.4. This only affects base request class. I can figure out what version is used when I import suds and go from there.  suds-jurko continues where suds left off, with better unicode support, and includes python 3 support. Let me know your thoughts, maybe not supporting suds 0.4 would work. I'm just worried about people that have a dependency on suds 0.4 in their env for other things. Although, that module is quite dated, not sure if its a problem.

**Comment by gtaylor** [comment]
As long as our setup.py is adjusted accordingly, I have no problems going with suds-jerko outright if it makes life better for everyone.

We can cut a release this weekend if you wanted to get that ready and update the changelog/version numbers.

**Comment by radlws** [comment]
I'll send that through shortly

**Comment by radlws** [comment]
Sorry, took a while, mostly testing with both py2 and py3. All there in #56  

I also tested with suds 0.4 on python2, still working with the old suds package.

**Comment by gtaylor** [comment]
Are we good to cut a new release?

**Comment by radlws** [comment]
Yeah its ready

**Comment by gtaylor** [comment]
I've added you as a collaborator. If you want to get us prepped for 2.0, we can get that up on PyPi.

**Comment by radlws** [comment]
2.0, or are we going with 1.2.0 ?

**Comment by gtaylor** [comment]
I'd lean towards 2.0 just to be safe. suds-jerko is still based on suds, but there has been enough change to where it's probably best to cover our asses and go 2.0.

**Comment by radlws** [comment]
Sure thing. It still works on suds 0.4 though, which is a good thing. I'll update the version numbers. Anything else required? The project is registered with you on pypi, not 100% sure on that but I think you have to upload it? I'm registered on there too so not sure if there is a collaboration option there.

**Comment by gtaylor** [comment]
Let me know what your username is on there and I can add you to the project.

**Comment by radlws** [comment]
Just emailed it

**Comment by radlws** [comment]
+1 me if it looks good, https://github.com/gtaylor/python-fedex/pull/58

**Comment by gtaylor** [comment]
All set! Feel free to cut the release when ready.

**Comment by radlws** [comment]
Done!

**Comment by radlws** [comment]
Is it possible to add `gregov` as a contributor? He would be able to review any future PRs.

**Comment by gtaylor** [comment]
Sure, done.

**Comment by radzhome** [comment]
Thanks

**Comment by radzhome** [comment]
Happy New Year to you!  I was wondering what you had in mind for the maintenance transition plan and what the next steps would be.  Thanks again.

**Comment by gtaylor** [comment]
I wanted to try to get this moved into its own org so that we can decouple the survival of the project from whoever is maintaining it at the time. But for now, I think we're far enough along for you to start merging things without waiting on me. Ditto for cutting releases.

**Comment by radzhome** [comment]
Not a bad idea, makes sense.

**Comment by radzhome** [comment]
I wanted to re-generate the documentation on pythonhosted, or maybe re-generate on readthedocs. What do you think?

**Comment by gtaylor** [comment]
I subjectively really like RTD. But as long as we've got something and it's up to date, we'll be doing better than most!

**Comment by radzhome** [comment]
Yeah its out of date at the moment... As for travis (I wanted to get the build logos in the readme), I'm getting: 

If this repository is already in active use, make sure it’s activated on your profile.

So I think creating the org first is required to get it all connected. May I suggest "python-fedex-devs" as the org name.

**Comment by radzhome** [comment]
Can you redirect https://code.google.com/p/python-fedex/ to this github project?

**Comment by radzhome** [comment]
Created a new org, you should be admin there now: python-fedex-devs

**Comment by radzhome** [comment]
As soon as you join, I'll make you owner.

**Comment by gtaylor** [comment]
Just moved the repo. We'll want to update any links that pointed at the old location.

**Comment by radzhome** [comment]
Sweet!  I updated copyright and authors. Great stuff! I think if we recruit more solid contributors. I think all core services are implemented for now. I'll close off this ticket.  I updated docs too but I will try to get read the docs version up soon.  Gonna write a blog entry soon too regarding python-fedex recent changes!
