### ISSUE TITLE
Just checking in

### ISSUE THREAD

**Issue by gtaylor** [python-fedex-devs/python-fedex#73]
Hello @radzhome and friends. I just wanted to check in and make sure you've got everything you need at this point. I don't want to be holding you up in any way, it looks like things are going well.

**Comment by radzhome** [comment]
Hey, yeah things are good here. Let me know if you have any feedback on the read the docs / sphinx docs I created.  Should I keep the epydoc html files or scrap them? I'l leave the 2.2v docs on pythonhosted but all new docs will go on readthedocs.

**Comment by gtaylor** [comment]
I'd just scrap the epydocs. Those things are ancient and probably pretty badly out of date now. Once you're done moving to RTD, I'd suggest taking the stuff down from Pythonhosted to avoid confusion. If they support redirects, that might be worth tossing up, but I wouldn't be too worried if not.

Looking good! I'm sure the users appreciate seeing the activity.
