### ISSUE TITLE
Recipient phone numbers required?

### ISSUE THREAD

**Issue by nathanielstenzel** [python-fedex-devs/python-fedex#75]
I work at a place that ships stuff using the Fedex Shipping Manager software. It does not seem to need a recipient phone number, but this module does. Am I doing something wrong? Should I give a number like "###-###-####" or "000-000-0000" or something?

**Comment by nathanielstenzel** [comment]
I am also having trouble finding out how to set the REF, PO, DEPT and INV fields of the label and setting the custom text at the top.

**Comment by nathanielstenzel** [comment]
By the way, I am a python programmer, so if these parts are not available, let me know where to look and I will fork your code and see what I can do.

**Comment by nathanielstenzel** [comment]
I also need to find out how to set up the saturday delivery flag.

**Comment by nathanielstenzel** [comment]
Where shipment is made by FedexProcessShipmentRequest.... shipment.RequestedShipment.SpecialServicesRequested.SpecialServiceTypes.append("SATURDAY_DELIVERY")
That seems to set up Saturday delivery.

**Comment by nathanielstenzel** [comment]
customer_reference = shipment.create_wsdl_object_of_type('CustomerReference')
	customer_reference.CustomerReferenceType="CUSTOMER_REFERENCE"
	customer_reference.Value = "your customer reference number"
	department_number = shipment.create_wsdl_object_of_type('CustomerReference')
	department_number.CustomerReferenceType="DEPARTMENT_NUMBER"
	department_number.Value = "your department number"
	invoice_number = shipment.create_wsdl_object_of_type('CustomerReference')
	invoice_number.CustomerReferenceType="INVOICE_NUMBER"
	invoice_number.Value = "your invoice number"
	shipment.RequestedShipment.RequestedPackageLineItems[0].CustomerReferences = [ customer_reference, invoice_number, department_number ]

The options are INVOICE_NUMBER, DEPARTMENT_NUMBER, CUSTOMER_REFERENCE, P_O_NUMBER

**Comment by radzhome** [comment]
Please look at the WSDL to see what is required. All wsdls are in the wsdl directory.

**Comment by nathanielstenzel** [comment]
Thanks for the reply, @radzhome . Well, it seems I figured out most of the stuff, even though it could be a bit easier. If you guys could make the 4 fields that I mentioned in the post before yours a little bit easier to access, I am sure people would appreciate it. If not, do you think you could include my little bit of code on the quick start page?
By the way, I love the project. I hope to get the green light for a project at work to start using python-fedex on the production FedEx servers within the next 2-4 weeks.

**Comment by radzhome** [comment]
Sure can you create a pull request so we can review what you want changed? Are you referring to the ship example: https://github.com/python-fedex-devs/python-fedex/blob/master/examples/create_shipment.py  The example does have the shippers phone number uncommented: `shipment.RequestedShipment.Shipper.Contact.PhoneNumber = '9012638716'`

**Comment by nathanielstenzel** [comment]
http://python-fedex.readthedocs.org/en/stable/quick_start.html That is from you guys too, right?

The 4 fields that I was referring to were INVOICE_NUMBER, DEPARTMENT_NUMBER, CUSTOMER_REFERENCE, P_O_NUMBER.

I did not actually make any changes to the code. I do have that example up above that could be useful for anyone using this or anyone who wanted to make a change though. I am not sure if I could justify doing that coding adjustment at work which is the only reason why I am interested in it at this time.

**Comment by radzhome** [comment]
I'll include them in the example if you think it will be useful for others. They are not required fields though. Thanks.
