### ISSUE TITLE
ReturnShipment Detail

### ISSUE THREAD

**Issue by deepakkapoor624** [python-fedex-devs/python-fedex#79]
Hi,
Is there any way to print return Label Detail in COD. As I can not find any details in create_shipment.py.

**Comment by radzhome** [comment]
Not sure what you're looking for exactly but did you look at the ShipService_v17.wsdl? There is a `CodCollectionType` and some other things in there for COD

**Comment by radzhome** [comment]
If you get an example going, feel free to contribute.  This is a wrapper around the fedex SOAP service so you can for sure do it if its available in the service itself.. Just have to look in the wsdl for the object you want to add.
