### ISSUE TITLE
Pickup request docs

### ISSUE THREAD

**Issue by noodlebreak** [python-fedex-devs/python-fedex#80]
Hi,

A request for pickup of shipment  by a Fedex agent - no documentation is given on RTD.
Is pickup implemented in this app? Currently, here I cannot find it:
http://python-fedex.readthedocs.io/en/latest/services.html

Shipping order creation, tracking, etc are given. But pickup is not mentioned anywhere. I've also seen a PR of pickup service, but it's not mentioned anywhere on how to use it. Also, there's not example for pickups in https://github.com/python-fedex-devs/python-fedex/tree/master/examples.

But I did find a pickup service unittest:
https://github.com/python-fedex-devs/python-fedex/blob/master/tests/test_pickup_service.py

So, does the code written in above test: This is the stuff to get a Fedex agent to come and pickup the shipment package, right? If so, I can test that out and this issue can be closed. Thanks.

**Comment by noodlebreak** [comment]
Also, I'm facing problems with ReadyTimestamp.

Basically, this was the error:

    INFO:fedex.response:FedEx Response <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body><CreatePickupReply xmlns="http://fedex.com/ws/pickup/v11"><HighestSeverity>ERROR</HighestSeverity><Notifications><Severity>ERROR</Severity><Source>disp</Source><Code>5044</Code><Message>Ready Time after Cutoff Time</Message><LocalizedMessage>Ready Time after Cutoff Time</LocalizedMessage></Notifications><Version><ServiceId>disp</ServiceId><Major>11</Major><Intermediate>0</Intermediate><Minor>0</Minor></Version></CreatePickupReply></SOAP-ENV:Body></SOAP-ENV:Envelope>
    E
    ======================================================================
    ERROR: test_rate (__main__.FedexCreatePickupRequestTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test_pickup_service.py", line 77, in test_rate
        pickup_service.send_request()
      File "../fedex/base_service.py", line 331, in send_request
        self._check_response_for_request_errors()
      File "../fedex/base_service.py", line 265, in _check_response_for_request_errors
        notification.Message)
    FedexError: Ready Time after Cutoff Time (Error code: 5044)


Now what I read about it in the docs, I found that ReadyTimestamp has to be lower than CutOffTime.
And this was the ReadTimeStamp in my request: 
`<ns0:ReadyTimestamp>2016-09-05T16:45:56</ns0:ReadyTimestamp>`

From the [docs](https://images.fedex.com/templates/components/apps/wpor/secure/downloads/pdf/201607/FedEx_WebServices_DevelopersGuide_v2016.pdf):

```
ReadyTimestamp Identifies the date and time the package will be ready for
pickup by FedEx. The time must be no later than the
CutOffTime, which can be discovered with the
PickupAvailabilityRequest. 
```

Which brings me to my actual question: We don't have PickupAvailabilityRequest, do we?
If I were to create it, how should I go about it? Little guidance would be great. Maybe I could put a PR to add PickupAvailabilityRequest.

**Comment by radzhome** [comment]
Check out the wsdl for pickup service. You're right there are no docs for pickup service but I did add a unit test. The user that provided the addition did not supply an example.
