### ISSUE TITLE
TrackingRequest incorrectly constructed from v10 WSDL

### ISSUE THREAD

**Issue by mmangione** [python-fedex-devs/python-fedex#89]
Was trying to track a package by reference number today. Found it to be impossible. 

I need to send country in this field along with the account number:
track.SelectionDetails.Destination

It should accept Address objects. It incorrectly expects a string. Adding the proper type causes a SchemaValidationError. Sending anything else to Fedex produces a failure in their system.

**Comment by yanpozka** [comment]
if you're searching for reference number you may want to take a look here https://github.com/python-fedex-devs/python-fedex/issues/83

**Comment by mmangione** [comment]
That's what I used. The problem is the incorrect construction from the WSDL.

**Comment by radzhome** [comment]
Yeah nothing we can do about that unless its fixed in V11

**Comment by radzhome** [comment]
Closing issue, bug with service not package.

**Comment by mmangione** [comment]
Hang on. This is not an error with the WSDL. This is an error with the construction of the WSDL by this package.

Look at the definition of track.SelectionDetails.Destination in the WSDL, it clearly says that it expects "Account" type. Yet, this package says it should expect a "string" type.

**Comment by mmangione** [comment]
Look man,

          <xs:element name="Destination" type="ns:Address" minOccurs="0">
            <xs:annotation>
              <xs:documentation>Only country is used for elimination of duplicate tracking numbers.</xs:documentation>
            </xs:annotation>
          </xs:element>

**Comment by mmangione** [comment]
Hello? This is not a bug with the service. You closed this ticket without any form of investigation.
