### ISSUE TITLE
Rate service error.

### ISSUE THREAD

**Issue by dbroblem** [python-fedex-devs/python-fedex#90]
Hi.. i have been trying to test the rate service, but keep getting errors. Currently it is an authentication error, but i have also received the following error.
account number and associates address is required for service type code 988   
THe latest error was obtained after changing the account numbers to my ltl account info sent when i signed up for a developer key. Any insights you can provide would be appreciated.

Rob

**Comment by radzhome** [comment]
I would address that question to FedEx api support, this library is just a wrapper to the soap api.
