### ISSUE TITLE
FedexValidatePostalRequest service issue

### ISSUE THREAD

**Issue by pji-odoo** [python-fedex-devs/python-fedex#93]
i wanted to validate postal code of US 
and used service >>  FedexValidatePostalRequest
but it seems it doesn't conside country code and check for provided country only
i am getting success results for other postal codes too!!
any suggestion related to this issue ?

after CONFIG and ShipDate details setting this two values,

1) avc_request.Address.CountryCode = 'US'
2) avc_request.Address.PostalCode = '12346'

**Comment by radzhome** [comment]
Not sure, I would check with FedEx. Seems like a question for them.
