### ISSUE TITLE
can't get trackdetails

### ISSUE THREAD

**Issue by yan1990y** [python-fedex-devs/python-fedex#99]
Hello,I use track service simply to get track details with tracknumber.
But in examples,I view track.response,there is no trackdetails,there is only "process success" info,but I need more detailed info(time,status and so on).Thanks for answer.

**Comment by tgehrs** [comment]
I was having the same issue -- fixed it by:

1. set the ProcessingOptions
2. delete FDXE as the CarrierCode


```
track.ProcessingOptions = 'INCLUDE_DETAILED_SCANS'
del track.SelectionDetails.CarrierCode
```

**Comment by radzhome** [comment]
I think this issue can be closed
